### ISSUE TITLE
The same with lambda expressions

### ISSUE THREAD

**Issue by pierrefevrier** [grasshopper7/cuke4-parameter-datatable#1]
Hi !

Thanks for these usefull samples.

I'm trying to convert the glue to lambda style.
But the following doesn't work:

```java
Given("the list lecture details are", (List<Lecture> lectures) -> {
	System.out.println("");
	System.out.println(lectures);
});
```

The error is: `cucumber.runtime.CucumberException: Can't use java.util.List in lambda step definition "the list lecture details are". Declare a DataTable argument instead and convert manually with asList/asLists/asMap/asMaps`

Do you know if there is a way to make it work ?

Thanks.

**Comment by grasshopper7** [comment]
Your issue somehow slipped through the cracks. I will have a look at this with lambdas and let you know. Thx

**Comment by grasshopper7** [comment]
DO not think this is possible. You will have to use a DataTable and convert manually. https://github.com/cucumber/cucumber-jvm/issues/936

**Comment by pierrefevrier** [comment]
Thanks for answering me.  
I really hope that we can find a solution to this problem one day :/
